# Generated by Django 3.0.8 on 2020-08-07 18:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='sets_id',
        ),
        migrations.AddField(
            model_name='set',
            name='workout_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workouts.Workout'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Sets',
        ),
    ]
