# Generated by Django 3.0.8 on 2020-08-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200731_1932'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('workouts', '0006_auto_20200822_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='oFUser',
        ),
    ]
