# Generated by Django 3.0.8 on 2020-08-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_auto_20200822_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='date_created',
            new_name='date',
        ),
    ]
